import React, { useState, useEffect } from 'react';
import { BASIC_LANDS } from '../../data/presetSets';
import confetti from 'canvas-confetti';
import { Sparkles, Layers, Plus, Minus, Download, HelpCircle, RefreshCw, CheckCircle2 } from 'lucide-react';

export function DeckBuilder({ draftedPool = [], onResetDraft }) {
  const [maindeck, setMaindeck] = useState([]);
  const [sideboard, setSideboard] = useState([]);
  const [landCounts, setLandCounts] = useState({ W: 0, U: 0, B: 0, R: 0, G: 0 });

  // Initialize: Put all drafted non-land spells into sideboard by default
  useEffect(() => {
    if (draftedPool && draftedPool.length > 0) {
      setSideboard([...draftedPool]);
      setMaindeck([]);
    }
  }, [draftedPool]);

  // Move card from Sideboard to Maindeck
  const moveToMaindeck = (card) => {
    setSideboard(prev => prev.filter(c => c.instanceId !== card.instanceId));
    setMaindeck(prev => [...prev, card]);
  };

  // Move card from Maindeck to Sideboard
  const moveToSideboard = (card) => {
    setMaindeck(prev => prev.filter(c => c.instanceId !== card.instanceId));
    setSideboard(prev => [...prev, card]);
  };

  // Calculate Auto Lands
  const autoAddLands = () => {
    const spellCount = maindeck.length;
    const landsNeeded = Math.max(0, 40 - spellCount);

    if (landsNeeded === 0) return;

    // Count color symbols in maindeck cards
    const colorSymbols = { W: 0, U: 0, B: 0, R: 0, G: 0 };
    maindeck.forEach(card => {
      if (card.colors) {
        card.colors.forEach(c => {
          if (colorSymbols[c] !== undefined) colorSymbols[c]++;
        });
      }
    });

    const totalSymbols = Object.values(colorSymbols).reduce((a, b) => a + b, 0);

    const newLands = { W: 0, U: 0, B: 0, R: 0, G: 0 };
    if (totalSymbols === 0) {
      // Default fallback split 9 Plains / 8 Islands if no colors
      newLands.W = Math.ceil(landsNeeded / 2);
      newLands.U = landsNeeded - newLands.W;
    } else {
      let allocated = 0;
      const sorted = Object.entries(colorSymbols).sort((a, b) => b[1] - a[1]);
      
      sorted.forEach(([col, count]) => {
        if (count > 0 && allocated < landsNeeded) {
          const share = Math.round((count / totalSymbols) * landsNeeded);
          newLands[col] = share;
          allocated += share;
        }
      });

      // Adjust rounding difference
      const diff = landsNeeded - Object.values(newLands).reduce((a, b) => a + b, 0);
      if (diff !== 0 && sorted[0]) {
        newLands[sorted[0][0]] = Math.max(0, newLands[sorted[0][0]] + diff);
      }
    }

    setLandCounts(newLands);
    confetti({ particleCount: 50, spread: 60, origin: { y: 0.8 } });
  };

  // Adjust land manually
  const updateLandCount = (color, delta) => {
    setLandCounts(prev => ({
      ...prev,
      [color]: Math.max(0, prev[color] + delta)
    }));
  };

  const totalBasicLands = Object.values(landCounts).reduce((a, b) => a + b, 0);
  const totalDeckCards = maindeck.length + totalBasicLands;

  const creaturesCount = maindeck.filter(c => c.isCreature).length;
  const nonCreaturesCount = maindeck.filter(c => !c.isCreature && !c.isLand).length;

  // Mana Curve histogram
  const curveCounts = { 0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, '6+': 0 };
  maindeck.forEach(c => {
    const cmc = c.cmc || 0;
    if (cmc >= 6) curveCounts['6+']++;
    else curveCounts[cmc]++;
  });
  const maxCurveVal = Math.max(1, ...Object.values(curveCounts));

  // Export Deck to MTG Arena format
  const exportToArena = () => {
    let arenaText = '// Deck generated by MTG Draft Academy\n';
    
    // Group maindeck cards
    const cardCounts = {};
    maindeck.forEach(c => {
      cardCounts[c.name] = (cardCounts[c.name] || 0) + 1;
    });

    Object.entries(cardCounts).forEach(([name, qty]) => {
      arenaText += `${qty} ${name}\n`;
    });

    // Basic lands
    Object.entries(landCounts).forEach(([col, qty]) => {
      if (qty > 0) {
        const landObj = BASIC_LANDS[col];
        arenaText += `${qty} ${landObj.type}\n`;
      }
    });

    // Sideboard
    arenaText += '\n// Sideboard\n';
    const sideCounts = {};
    sideboard.forEach(c => {
      sideCounts[c.name] = (sideCounts[c.name] || 0) + 1;
    });
    Object.entries(sideCounts).forEach(([name, qty]) => {
      arenaText += `${qty} ${name}\n`;
    });

    // Download text file
    const blob = new Blob([arenaText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'mtg_draft_deck.txt';
    link.click();
  };

  return (
    <div className="max-w-7xl mx-auto px-4 py-8 space-y-8 animate-fadeIn">
      
      {/* Header Bar */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 shadow-xl flex flex-col md:flex-row items-center justify-between gap-6">
        <div>
          <div className="flex items-center gap-2 text-amber-400 font-extrabold text-xs uppercase tracking-wider">
            <Sparkles size={16} />
            <span>Fase Finale — Guida al Deckbuilding</span>
          </div>
          <h2 className="text-3xl font-black text-white mt-1">
            Costruisci il tuo Mazzo da 40 Carte
          </h2>
          <p className="text-sm text-slate-400 mt-1">
            Sposta le carte dal tuo Pool al Mazzo. Clicca su "Calcola Terre" per aggiungere le terre base ideali.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          <button
            onClick={autoAddLands}
            className="px-5 py-3 rounded-2xl bg-gradient-to-r from-amber-500 to-yellow-400 hover:from-amber-400 hover:to-yellow-300 text-slate-950 font-black text-sm shadow-lg flex items-center gap-2 transform hover:-translate-y-0.5 transition-all"
          >
            <Sparkles size={16} />
            <span>CALCOLA & AGGIUNGI TERRE AUTOMATICAMENTE</span>
          </button>

          <button
            onClick={exportToArena}
            className="px-4 py-3 rounded-2xl bg-slate-800 hover:bg-slate-700 text-slate-200 font-bold text-sm border border-slate-700 flex items-center gap-2 transition-colors"
          >
            <Download size={16} />
            <span>Esporta in MTG Arena</span>
          </button>
        </div>
      </div>

      {/* Stats Dashboard Grid */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
        
        {/* Left Stats & Coach Analysis */}
        <div className="md:col-span-5 space-y-6">
          
          {/* Deck Counters Card */}
          <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 space-y-4 shadow-xl">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <span className="font-extrabold text-sm text-slate-200">Totale Carte Mazzo</span>
              <span className={`text-xl font-black px-3 py-1 rounded-xl border ${
                totalDeckCards === 40
                  ? 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40 ring-2 ring-emerald-500/30'
                  : 'bg-amber-500/20 text-amber-300 border-amber-500/30'
              }`}>
                {totalDeckCards} / 40
              </span>
            </div>

            <div className="grid grid-cols-3 gap-2 text-center text-xs">
              <div className="bg-slate-950 p-3 rounded-xl border border-slate-800">
                <span className="text-slate-400 block font-bold">Magie (Creature)</span>
                <span className="text-base font-black text-amber-400">{creaturesCount}</span>
              </div>
              <div className="bg-slate-950 p-3 rounded-xl border border-slate-800">
                <span className="text-slate-400 block font-bold">Altre Magie</span>
                <span className="text-base font-black text-sky-400">{nonCreaturesCount}</span>
              </div>
              <div className="bg-slate-950 p-3 rounded-xl border border-slate-800">
                <span className="text-slate-400 block font-bold">Terre Base</span>
                <span className="text-base font-black text-emerald-400">{totalBasicLands}</span>
              </div>
            </div>

            {/* Basic Lands Selector */}
            <div className="space-y-2 pt-2 border-t border-slate-800">
              <span className="text-xs font-bold text-slate-400 block">Gestione Terre Base:</span>
              <div className="space-y-1.5">
                {Object.entries(BASIC_LANDS).map(([col, landObj]) => (
                  <div key={col} className="flex items-center justify-between bg-slate-950 px-3 py-2 rounded-xl border border-slate-800 text-xs">
                    <div className="flex items-center gap-2">
                      <span className="font-bold text-slate-200">{landObj.name} ({col})</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => updateLandCount(col, -1)}
                        className="p-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-300"
                      >
                        <Minus size={12} />
                      </button>
                      <span className="w-6 text-center font-mono font-bold text-white">{landCounts[col]}</span>
                      <button
                        onClick={() => updateLandCount(col, 1)}
                        className="p-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-300"
                      >
                        <Plus size={12} />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>

          </div>

          {/* Mana Curve Graph Card */}
          <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 space-y-4 shadow-xl">
            <h4 className="font-extrabold text-sm text-slate-200">Curva di Mana (CMC)</h4>
            <div className="flex items-end justify-between h-32 pt-4 px-2 bg-slate-950/60 rounded-2xl border border-slate-800">
              {Object.entries(curveCounts).map(([cost, count]) => {
                const heightPercent = (count / maxCurveVal) * 100;
                return (
                  <div key={cost} className="flex flex-col items-center flex-1 h-full justify-end gap-1">
                    <span className="text-[10px] font-mono text-amber-400 font-bold">{count}</span>
                    <div
                      style={{ height: `${Math.max(8, heightPercent)}%` }}
                      className="w-full max-w-[24px] bg-gradient-to-t from-amber-600 to-yellow-400 rounded-t-md transition-all duration-300"
                    />
                    <span className="text-[10px] font-mono text-slate-400">{cost}</span>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Coach Advice Analysis Card */}
          <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 space-y-3 shadow-xl">
            <div className="flex items-center gap-2 text-amber-400 font-bold text-sm">
              <CheckCircle2 size={18} />
              <span>VALUTAZIONE COACH MAZZO:</span>
            </div>
            <div className="text-xs text-slate-300 space-y-2 leading-relaxed">
              {totalDeckCards === 40 ? (
                <p className="p-3 bg-emerald-500/10 border border-emerald-500/30 rounded-xl text-emerald-300">
                  🎉 <strong>Mazzo Completo di 40 carte!</strong> La composizione è equilibrata e pronta per la partita.
                </p>
              ) : totalDeckCards < 40 ? (
                <p className="p-3 bg-amber-500/10 border border-amber-500/30 rounded-xl text-amber-300">
                  ⚠️ Hai {totalDeckCards} carte nel mazzo. Aggiungi ancora {40 - totalDeckCards} carte o terre per raggiungere le 40 carte ideali.
                </p>
              ) : (
                <p className="p-3 bg-rose-500/10 border border-rose-500/30 rounded-xl text-rose-300">
                  ⚠️ Il tuo mazzo ha {totalDeckCards} carte. Nel limited è consigliato rimanere a 40 carte esatte.
                </p>
              )}
            </div>
          </div>

        </div>

        {/* Right Maindeck & Sideboard Grids */}
        <div className="md:col-span-7 space-y-6">
          
          {/* Maindeck Spells List */}
          <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 space-y-4 shadow-xl">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <h3 className="font-extrabold text-base text-slate-100 flex items-center gap-2">
                <Layers size={18} className="text-amber-400" />
                <span>Mazzo Principale ({maindeck.length} Magie)</span>
              </h3>
              <span className="text-xs text-slate-400">Clicca su una carta per spostarla nel Pool</span>
            </div>

            {maindeck.length === 0 ? (
              <div className="text-center py-10 text-slate-500 border border-dashed border-slate-800 rounded-2xl text-xs">
                Il mazzo è ancora vuoto. Clicca sulle carte nel tuo Pool sottostante per aggiungerle!
              </div>
            ) : (
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 max-h-96 overflow-y-auto pr-1">
                {maindeck.map(card => (
                  <div
                    key={card.instanceId}
                    onClick={() => moveToSideboard(card)}
                    className="group cursor-pointer p-2.5 bg-slate-950 hover:bg-slate-900 border border-slate-800 hover:border-rose-500/50 rounded-xl transition-all flex items-center justify-between text-xs"
                  >
                    <div className="truncate">
                      <span className="font-bold text-slate-200 group-hover:text-rose-400 block truncate">{card.name}</span>
                      <span className="text-[10px] text-slate-400">{card.typeLine?.split('—')[0]}</span>
                    </div>
                    <span className="text-amber-400 font-mono text-[10px] font-bold ml-1">{card.manaCost}</span>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Sideboard / Drafted Pool */}
          <div className="bg-slate-900/60 border border-slate-800 rounded-3xl p-6 space-y-4">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <h3 className="font-extrabold text-base text-slate-100">
                Pool Carte Inutilizzate ({sideboard.length})
              </h3>
              <span className="text-xs text-slate-400">Clicca per inserire nel Mazzo</span>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 max-h-72 overflow-y-auto pr-1">
              {sideboard.map(card => (
                <div
                  key={card.instanceId}
                  onClick={() => moveToMaindeck(card)}
                  className="group cursor-pointer p-2.5 bg-slate-950/80 hover:bg-slate-900 border border-slate-800 hover:border-emerald-500/50 rounded-xl transition-all flex items-center justify-between text-xs opacity-75 hover:opacity-100"
                >
                  <div className="truncate">
                    <span className="font-bold text-slate-300 group-hover:text-emerald-400 block truncate">{card.name}</span>
                    <span className="text-[10px] text-slate-500">{card.typeLine?.split('—')[0]}</span>
                  </div>
                  <span className="text-amber-400 font-mono text-[10px] font-bold ml-1">{card.manaCost}</span>
                </div>
              ))}
            </div>
          </div>

        </div>

      </div>

    </div>
  );
}
